== 那些闪烁着光芒的民族魂魄

《黑暗传》就像是一部具有魔力的书，一旦爱上她，就无法自拔，越陷越深，这是我三周来的真实感受。我就像是一个孩子，站在滚滚的大河边，看着翻滚的浪花和漩涡，越看越觉得深邃，越看越觉得奇妙，那种势不可挡的力量，一阵阵的冲击着岸边的我。

我反复的看每一个原始版本、每一个整理版本（胡崇峻、吴承清、陈人麟三位前辈）以及诸位老先生的评述文章，以帮助自己理清整个《黑暗传》的脉络、故事、情节，若不如此，是断然不敢说要来做整理工作的。

终于完成了一个暂时还可以接受的版本，可以呈现给早已经在等待的朋友们，而我也可以抽离出来，回到生活，做一些更重要的事情。那些还在心头盘旋的困惑也已经列到了`修订日志`上面，期待能接触到更多资料，以做补充。

等到快要完工的时候，我才在网络上寻找胡崇峻、吴承清、陈人麟、刘守华几位老先生的资料以及照片，得益于他们的工作，我才可以看到宏伟瑰丽的《黑暗传》，才可以读懂他，才可以有胆量要做一点工作，所以，我应该认识他们。在《黑暗传》里面，拜师似乎都是很容易的事情，当然这种容易的前提是机缘使然，我想虽然并未谋面，这些老先生已经是我的老师了。

前些天在吴蓓老师家，大陆以及台湾的几位华德福老师通过微信语音交流《黑暗传》的教学经验，很是精彩。也是在那时，我才知道胡崇峻先生已经在今年的6月4日驾鹤西去，一阵惊愕。为此史诗，毕其一生之力，我以为这与《黑暗传》里那些闪烁着光芒的民族魂魄并无二致。而陈人麟先生今年也已经76岁了，刘守华教授81岁了，吴承清先生71岁了……正是他们的努力，让曾经的微光，得以持续闪烁、闪耀！让后来的我们，还可以寻找到这个民族“最早的血脉和记忆”。

在长篇小说《灵山》之中，面对《黑暗传》的失传，高行健发出了痛彻心扉的控诉：“还哪里去找对灵魂的敬畏？哪里还能再找到这应该端坐静穆乃至于匐伏倾听的歌？该崇敬的不去崇敬，只崇拜些莫名其妙的东西！一个灵魂空虚荒凉的民族！一个丧失了灵魂的民族！”——多么的热切，却又是多么的无奈，只有读懂的人才能理解。

但是，或许我们可以不那么悲观，因为这仅仅片段的文本就已经开始撞击着我的心——我将珍惜这珍宝，让他涤荡我的血液，并希望将这份热情传递给另一个人——哪怕只有很少的人在这珍视的行列，就是点亮的微光，就是娇嫩的希望。虽然全本的《黑暗传》至今未能寻到，但是在冥冥之中，我却感觉到他并未失传，只是藏在茫茫神农架大山之中的某一个角落，总有一天，可以找到，重现光芒……

此时此刻，在我心里产生了两个奇异的想法，也一并分享：

首先，我竟并不在意所谓学术界的那些奇谈怪论，尽管他们并不以为《黑暗传》是史诗（最后只是折衷称为神话历史叙事长诗），甚至不能代表汉族，这也只是他们的观点，我所在乎的绝不是僵化陈腐的理论框架，而是《黑暗传》本身带给我的是什么？我的心灵的回响是什么？所有的价值都在文本和歌唱的声音里，也只是在这里。

其次，诸位前辈所忧心的《黑暗传》传承之困，诸如歌师减少、演唱机会减少……我也以为完全可以换个思路来讲，对于《黑暗传》，我们是否可以将其分为两个部分来看？第一是”在神农架的《黑暗传》”，在神农架及其周边的流传地区，《黑暗传》是丧歌、是演唱、是大山里的声音回荡，所以若没有歌师，没有演唱，没有了生存发展所依赖的社会基础，自然是传承危急。但是跟许多的非物质文化遗产面临的困境一样，现实社会的剧变是无力阻挡的，是客观的，我们也不可能一厢情愿的使其回到从前。所能做的是“保育”和“活化”——继续的搜集和整理、支持歌师的传承、营造良性的社会环境……第二是“整个汉民族的《黑暗传》”，我们从神农架走出来，站在整个民族的视角来看，如何让《黑暗传》真正的能够走近每一个人、靠近每一颗心，被阅读和学习，成为滋养民族魂魄的源泉？这应该也是一种传承。

如果说“在神农架的《黑暗传》”发展日渐微弱，如同越流越窄的溪流，总怕有一天就断了；那么“整个汉民族的《黑暗传》”则变成了如同从“三江源”（神农架是源头）咆哮而下的巨流，在远方有亿万干涸的灵魂等待被滋润，如能够推动让这股水流朝此方向奔去，当不负“汉民族的创世史诗”这一名号。

当然，离开了神农架的《黑暗传》，故事不变，形式却要变化，作为丧歌来演唱自然是不再。文本作为核心，或是诵读、或是唱诵或是其他艺术形式、或者是进入到孩子们的课堂里，成为神话、意识发展、创世等课题的学习内容，透过学习，滋润现在及未来的孩子们，流入他们的血液，支撑他们的脊梁……也是一件值得期待的美事。

值得高兴的是，在华语地区的华德福学校中，《黑暗传》的学习早已经开始，所呈现出来的教学效果也却如以上所言，让人惊喜。不少的老师，也在阅读和学习《黑暗传》，以寻找适合的方式带入课堂，当然这中间也遇到不少的问题，这也就是为什么会有`彩蝶整理版`的一个原因。

作为适于教育和公众阅读的《黑暗传》，我以为有两个特点是至关重要的：第一是清晰的主题脉络，不至于云山雾罩，难以靠近；第二是鲜活的故事描述，尤其是那些能够展现英雄形象和民族魂魄的细节，要有极强的画面感，而不是含糊而过；依此来看，目前所能看到的版本都不太合适。彩蝶整理版会紧紧抓住这两个需要来不断的补充和完善，以提供给有心之人。

当然，不可能一蹴而就，由于资料的匮乏，很多细节尚待增补，会在以后的版本里一一呈现，敬请期待，也欢迎大家给予反馈。

昨天还看到一则很有趣的“旧闻”，2008年的时候，有一部叫做《复活的三叶虫》的电影，其中有《黑暗传》的片段做插曲，本想邀请胡崇峻先生演唱，但那时候他已经失明，就找了另外一位专业歌手，结果这位歌手进了录音棚却不敢唱，因为他听到了关于《黑暗传》“魔咒”的一些议论，惧怕《黑暗传》对胡崇峻的“魔咒”有一天也落在自己身上。然后导演就打电话给胡崇峻先生，跟歌手沟通。胡先生给这位歌手讲了自己的故事，并耐心劝解，力证《黑暗传》的所谓“魔咒”只是对全篇掌握或通篇咏唱的人而言，而电影的插曲只需要唱出其中的一个小章节，完全够不成“魔咒”的要素，该名歌手才点头同意完成了插曲的演唱。

看完这个故事，我不禁感觉到胡先生的幽默，不过也竟不自觉的摸了摸眼睛。那就写到此处吧，下一个版本见！

名下
2016年8月25日
