[preface]

[[foreword-section, foreword]]
== 前言

尽管神农架《黑暗传》被誉为“汉民族的创世史诗”，作为"汉民族最早的血脉和记忆"使读到他的人兴奋不已，但终究还只是局限在学术圈和华德福社群，相对于近11.6亿的汉族人口，读者难有万分之一。

即便如此，由于目前流传（整理）版本存在的问题，大部分的读者也难以在心里建立起清晰的图景，常常是“仰望却无法靠近”。笔者斗胆想要在前人的工作基础上修订出一个“轮廓清晰”且“画面感强”的适于教育和公众阅读的版本，唯希望可以让更多人通过阅读，寻觅到藏在文字中间和自身血脉里，彼此呼应的民族魂魄。

为了让读者对《黑暗传》有更多的了解，在前言部分我提供了两篇辅助阅读的文章：第一篇《黑暗传》十问，是我综合所能看到的资料，整理出来的以为关键的问题；第二篇则是陈人麟先生多年前的成果，极具价值。

接下来，开始你神奇的旅程吧——回到千万年前，回到这个民族的最初！

---

=== 《黑暗传》十问
[qanda]

《黑暗传》是一部什么书？::

  《黑暗传》是流传在神农架及其邻近地区的一部民间盘歌唱本。它采取多种口头与书面文本世代相传，作为“孝歌”、“丧鼓歌”由大歌师以隆重的形式演唱。它以有关盘古氏开天辟地结束混沌黑暗，人们崇敬的许多文化英雄在洪荒时代艰难创世的一系列神话传说为叙说中心。它讲宇宙最初是一团气，清浊不分，一片黑暗，故名。又名《混沌传》、《混元记》。

《黑暗传》讲的是什么时候的什么故事？::

  《黑暗传》演绎了自宇宙之初直到三皇五帝时代的漫长历史演变进程，涉及了众多不见经传、鲜为人知的创世神话人物和故事，是一部史前社会的神话史诗。根据神农架民间歌手张树艺和曹良坤两位老先生（1986年张83岁，曹75岁）的回忆，全本《黑暗传》长达3万多行，它分为四大部分，第一部分《先天》讲宇宙自黑暗而混沌而玄黄的演变过程，第二部分《后天》讲盘古开天地，日月上天庭，万物初生，人类始创的故事，第三部分《泡天》讲天地又历经了洪水的多次磨难，才再创了人类社会，第四部分《治世》讲三皇五帝的生平业绩。

《黑暗传》是如何被发现的，其间又有什么样的感人故事？::

  这是因为《黑暗传》的手抄本最早是在神农架林区的民间发现的，加之有些神话人物和故事情节也与邻近地区的不尽一致，故湖北省民研分会1986年将其八种原始资料汇编成集时题名《神农架<黑暗传>》。
  好。1983年，神农架林区文化馆干部胡崇峻、吴承清v龚万文等同志奉命搜集民间歌谣，最早在松柏镇农民张忠臣老先生处觅得一本题为《黑暗传》的手抄本，随后又在几户农家搜集到几本同名的抄本。胡崇峻同志将其一部分收录在他主编的《神农架民间歌谣集》中，名之“长篇神话故事歌”，集子印出后，有关部门认为内容不够健康，未敢散发。最早对其发生兴趣的是华中师大中文系教授刘守华先生，刘先生现任民研湖北分会会长，他认定这是一部长篇神话史诗，并在一次全国性学术会上披露了有关情况，湖北日报随即发了报道。胡崇峻同志又将部分原始资料寄给著名神话学家袁轲先生，袁先生复信称之为“极可珍贵的资料”，是“广义的神话史诗”。至止方引起国内外学者的高度重视和广泛关注。

《黑暗传》的发现有何价值？::

    《神农架V黑暗传>》被有关专家学者视为“首部汉族长篇创世史诗”，其最重要的价值便在于它纠正了一个历史错误，填补了中国文学史上一项空白。在此之前，外国学者一直认定汉民族不可能有自己的创世史诗，我国学者也承认长期没有发现汉民族的创世史诗。

围绕《黑暗传》是否为汉民族创世史诗的问题学者们有何争议？::

    是的，学术争鸣属正常现象。不过对此提出异议的学者很少，至今我们仅知道一位，他便是美籍华裔学者，现在圣地亚哥加州大学任比较文学教授的郑树森先生。他曾撰写《（黑暗传>是不是汉族长篇史诗》一文，载于《上海师范大学学报》哲学版1990年第一期。该学报又于1992年第4期发表了尹笋君先生的商榷文章。

称《黑暗传》为“汉族创世史诗”有何依据？::

    史诗有英雄史诗和创世史诗之分，堪称创世史诗者必具两大要素，即诗的形式和开辟神话的内容。《黑暗传》是诗，句型以五言和七言为主，长达数千行；《黑暗传》属开辟神话，专讲宇宙和人类社会的形成经过，恰好符合创世史诗的要求。

《黑暗传》是何时形成的？怎样形成的？::

    应该说是逐步形成，不断充实完善的。《黑暗传》属民间盘歌，歌手们多是不请自到的，都视歌坛如战场，都有技压群芳的心理，都以能演唱古史显示自己学识的渊博。因此，第一位歌手唱民国故事，接唱者必讲明清，再唐宋、再三国、再秦汉、再春秋战国、再夏商周，以致三皇五帝、盘古开天、黑暗混. 沌，历史便越来越久远了，这是一个方面。另一方面是，一位歌手唱到盘古分天地，另一位想难倒对方，常提出盘古父甚母谁、何时出生、怎样开天、如何辟地等问题，越问越奇，内容也便越来越丰富了。至于《黑暗传》的成书时间问题，我认为也应从两个方面看。一方面从手抄本上记载的木刻本的年代（一为清道光7年，一为清光绪14年）和神农架的有关历史资料来分析，可推断至迟在明末清初已有《黑暗传》木刻本问世；另一方面应承认，早在此之前《黑暗传》故事便已成形，并在民间广为流传了。

《黑暗传》何以在神农架被保存下来？::

    这与神农架特殊的环境条件有关。其一，这儿是一片广袤的原始森林区，居民们长期保持着原始的耕作方式，当然也保持着古老的文化习俗；其二，这儿封闭阻塞数千载，受外来文化的影响相对少，传统文化因而能保持固有的特色；其三，这儿“山高皇帝远”，成了古文化的避风港、避乱所。但是， 在那“史无前例”的年月，《黑暗传》也曾遭受灭顶之灾。我们搜集到的几个抄本都是被歌手们当时藏在岩洞或埋在地下的， 这便是它们都严重残缺不全的原因。

《黑暗传》是在什么场合，怎样演唱的？::

    《黑暗传》只在丧歌歌坛演唱。当地民俗，凡有丧事，孝家必开丧鼓歌坛，一般要唱二夜。丧歌的内容很广泛，仅有唱本可依的就有“四游八传”，《黑暗传》即属“八传”之一。丧歌演唱时有鼓锣伴奏，歌唱者可以兼鼓手、锣手，也可以不兼，乐手和歌手都要不停地围着棺材转，边走边唱，中间不得停歇。 +
    即使在神农架，孝歌场上能听到《黑暗传》的机会也很少，这有两方面原因。一是《黑暗传》太深奥，一般歌手不敢唱，怕答不上来或答错了出洋相；二是《黑暗传》不尽合儒家思想，为正统观念所排斥，与之相对的唱本《纲鉴》中就有“唱歌莫唱《黑暗传》，它把混沌扯稀乱”的词儿。


《黑暗传》的搜集、整理和研究方面现状如何、困难有哪些？::

    原始资料的搜集工作从80年代初到如今一天也未间断过。1986年7月，民研湖北分会整理编印了《汉族长篇创世纪史诗神农架<黑暗传）多种版本汇编》，该汇编本共收录了8种版本的原始资料。1991年，陈人麟先生对上述原始资料进 ， 行分析比较，写成《神农架V黑暗传>原始资料内容述评》一文，初步理出了故事的脉络，发现了一些错漏。1992年，胡崇峻先生又从林区新华乡农民唐运清处觅得一个抄本，该抄本关于三番洪水、三分天地的故事十分新颖，吴承清先生予以吸收整理出《黑暗传》第一个比较完整的唱本。1993年，陈人麟先生综合9种原始资料，再次整理出一部唱本，长达2100多行，是迄今最长，内容最丰富的《黑暗传》唱本。 +
    问：研究《黑暗传》您有些什么新发现，新认识？ +
    答：有，而且很多，主要是下列方面。第一，我认为《黑暗传》集上古神话故事之大成。从黑暗老祖到三皇五帝，计有几百个神话人物，上千个神话故事，其绝大多数都不见经传，古代典籍上有记载的，也都是零零散散，残缺不全。可在《黑暗传》里，它们都被组合起来了，形成了一个整体。专家指出《黑暗传》极大地丰富了中国上古神话的宝库，实在不过分。第二，我认为《黑暗传》应是中华民族的创世史诗，集中华各民族创世神话之大成，诗中诸如浪荡子吞天、盘古开天、洪水泡天、葫芦造人、伏羲女娲婚配、三皇五帝等创世神话故事也都保存在一些少数民族的民间传说或歌谣之中。第三，我认为《黑暗传》是中华民族著名创世英雄生平业绩的民歌专章，诸如对盘古、伏羲、神农、轩辕等民族始祖的讲述都尽纳了史籍记载和民间传说的精华，塑造了丰满的人物形象，展开了完整的故事情节。第四，我认为《黑暗传，》能启迪我们对宇宙和人类社会起源问题的思考。它认为宇宙之初乃气体了团，直至清气上升， 浊气下沉才形成天地，这显然有科学道理。它解释人类起源于海洋，正和英国学者哈代的论断相吻合，更足以发人深思。第五，我认为《黑暗传》为我们研究史前社会的历史提供了宝贵资料。诸如按《黑暗传》推断，三皇（天皇、地皇、人皇）时代属人类社会的母系氏族时期，伏羲氏首制婚姻礼，标志着父系氏族的开端。神农时代，原始农耕开始兴起，轩辕氏靠征战而登上帝位，则是社会进化的又一标志。一夫多妻制始于少吴时代，家传天下也非始自大禹，唐尧时代已有私有制产生……它们已引起史学家重视。 +
    研究工作还有些什么困难？ +
    答：最大的困难还是仍感原始资料奇缺，已搜集到的9个抄本都是残缺不全的若干片断，彼此对照既多矛盾处，又多讹误处，诸如江沽造水土这样的重要内容至今尚属空白。另一方面的困难是对许多问题还不好解释，譬如为什么《黑暗传》竟揉合着儒、道、佛各家思想？几个再造人类的神话该怎样统一？三个女娲是否同属一人？

=== 试论《黑暗传》的非物质文化遗产性

**作者**：陈人麟 **原刊**：神农架林区非物质文化遗产保护名录丛书《黑暗传》

非物质文化遗产概念中的非物质性，是指以满足人们的精神生活需求为目的的精神生产这层涵义上的非物质性。联合国《保护非物质文化遗产国际公约》指出，非物质文化遗产涵盖五个方面的项目，即口头传说和表述，包括作为非物质文化遗产媒介的语言；表演艺术；社会风俗、丰L仪、节庆；有关自然界和宇宙的知识和实践和.传统的手工艺技能。国务院《关于加强文化遗产保护工作的通知》说，文化遗产包括物质文化遗产和非物质文化遗产。非物质文化遗产是指各种以非物质形态存在的与群众生活密切相关、世代相承的传统文化表现形式，包括口头传统、传统表演艺术、民俗活动和礼仪与节庆、有关自然界和宇宙的民间传统知识和实践、传统手工艺技能等以及与上述传统文化表现形式相关的文化空间。

《黑暗传》是部孝歌，曾广泛流传于鄂西、川东、湘西等山区的民间，神农架林区的歌手们至今还在演唱。比照上述对非物质文化遗产的定义，它无愧于一份极可珍贵的非物质文化遗产。

#### 《黑暗传》来自于丧鼓歌场

在神农架山林极其周边地区，民间历来把办丧事看的很重，素有“喜事可以不办，丧事不可怠慢”之说。但凡有人过世，无论是男是女、是老是少，也无论是贫是富、是贵是贱，孝家都一定要为之办丧事。办丧事就必须“打丧鼓”，唱丧歌（孝歌），而且是从亡人辞世的当天夜晚开始打，直打到出棺才结束。丧鼓歌场上总是歌手云集，他们自我表现的欲望都特强， 而且多以歌场为战场，多想借机与他人比个高低。歌手们是轮番上场的，由于“惟知前朝古代事，才算学识渊又博”，因此大家竞相“讲古”，越讲越古，前面歌手若唱的是民国故事，接腔者必唱明清典故，这样一朝一代往前推，便一直推到了三皇五帝、盘古开天地之前。歌场还多用“盘歌”来展开情节，无论自问自答，或者你问我答，都要追根求底，因此问题也越问越奇，越问越刁钻。譬如“歌师唱歌莫消停，再把盘古问一声，请教歌场老先生。盘古分开天和地，又有何人来出生？盘古还是归天界？还是人间了终身？”又如“歌师提起混沌祖，我将混沌问根古，混沌之时啥没有。 谁是混沌父？谁是混沌母？混沌出世啥时候？还有什么在里头？歌师对我讲清楚，我拜歌师为师傅。”《黑暗传》就是这样慢慢被无数歌手盘出来、推成型的。

#### 《黑暗传》反映了先民的宇宙观

《黑暗传》故事分“先天”、“后天”、“泡天”和“治世”四大部分，它集远古创世神话之大成，讲述了宇宙起源、天地出现和人类诞生、社会形成的漫漫历程，集中反映了先民们的宇宙观。

《黑暗传》讲，宇宙原本是一个大气团，气团内清浊不分，啥也没有，只现一片黑暗，由黑暗老祖掌管。不知道经过了多少年、多少代，气团内逐渐变成了混沌状态，就像小鸡刚孵成时蛋壳内的景象一样，称之为混沌。其时，混沌老祖接替了黑暗老祖，成为了宇宙的主宰。混沌时期长达几千万年，其间，宇内连续发生了几件大事：首先是出现了海洋。海洋是经过一十六代神祖的不懈努力，最后才由江沽皇造成的，海水来自被他熔化了的玄冰。接着，海洋里长出了荷叶，荷叶上托着一颗晶莹剔透的露水珠，这颗露水珠便是地球的胚胎，称之为“生天之根”。浪荡子到海边游玩，发现了这颗露珠，感到稀奇，正要伸手去摘时，奇妙子也赶到了，他是奉师命专门来取“生天之根”的。浪荡子不信邪，竟抢先把露珠一口吞进了肚子。玄黄老祖闻讯，不禁勃然大怒，当即祭起法宝，擒杀了浪荡子，并将其尸分五块，抛入了海洋。从此，海洋中升出了昆仑山，世界也才分出了陆海和高低。再后来，玄黄老祖又几经鏖战，收服了混沌，成为了新的主宰。此时宇内虽然清浊二气仍然没有分开，但却呈现出了天玄地黄的新景象。昆仑山凝聚着天精地灵、五行之气，盘古在它生成之时便开始孕育，四万八千年后终于来到了世上。盘古出世后，天地仍然被包在昏暗的气团内，他先借助一把神斧、一只神錾和一根神钎，又砍又凿又戳，清气不断地上浮，终于成了天；浊气不断地下沉，终于成了地。他立身其间，天地因此而得以逐渐稳住。接着，他又前往咸池，几经周折，才请动日月两君上了天庭，黑暗因此而永远结束，世界从此才有了光明。天上亮的除了日月，还有星星，星星就是日月的众子孙。此时，世界既有了水土，又有了阳光，万物得以滋生了，一些神灵和生物也开始慢慢地变成了人形，称之为“人类初造”。但是，人类世界的劫数依然未尽，随后又有三番洪水接踵而至。洪水多因恶龙争斗而起，洪水泛滥，淹没了山河，吞噬了万物，世界又恢复到了黑暗混沌状态。洪水过后，世界上的真人只剩下了一对兄妹，他们是借助一只大葫芦的庇护才保住性命的。经弘钧老祖苦口相劝，由一只金龟做媒，兄妹才答应结成婚姻。这对兄妹其实就是伏羲和女娲（前世），他们结为夫妻，生儿育女，女娲嫌人太少了，又捏土造出了许多人。人类社会从此才逐渐形成。

从人类诞生，到“治世”社会形成，也经历了漫长的历程。最初是天皇分四季、地皇定时辰、人皇划九州，继八十女皇后才有五帝相继建功立业：伏羲氏创八卦、治礼仪、造琴弦，神农氏创农耕、兴医药、开集市，轩辕氏做甲子、兴算术、制衣襟，帝唐尧选才能、兴禅让，帝虞舜传大禹，治洪水。至此才标志着人类社会走上了健康发展的轨道，《黑暗传》故事也到此结束。

#### 《黑暗传》无愧“史诗”之称

《黑暗传》无愧于“史诗”之称，它的发现纠正了西方学者关于汉民族不可能产生自己的史诗的历史偏见。

所谓“史诗”，从字面上解释当是“史”和“诗”的统一体，或者说是以诗歌形式演唱历史内容的民间文学作品。《黑暗传》完全符合这一基本特征， 因为它以七字句为基本句式，以“三起头”（即每个歌段的前三句必须表达一个完整意思，第三句末用句号）为歌段结构特点，讲究平仄，讲究押韵， 是一篇长篇叙事诗，不仅读起来朗朗上口，听起来更悦耳动听。它叙述了从“先天”到“治世”的漫漫历程，是一部宇宙演变史和人类社会的“史前史”。

《黑暗传》也完全符合辞书对“史诗”含义的解释。《辞海》是这样解释的：史诗指古代叙事诗中的长篇作品。反映具有重大意义的历史事件或以古代传说为内容，塑造著名英雄的形象，结构宏大，充满着幻想和神话色彩。《黑暗传》洋洋万余行，当然是“古代叙事诗中的长篇作品”；讲述的是宇宙演变的神话传说，当然是“具有重大意义的历史事件或以古代传说为内容”；突出了玄黄、盘古乃至三皇五帝等创世始祖的业绩，当然也塑造了“著名英雄的形象”，而且“充满着幻想和神话色彩”。

#### 《黑暗传》是汉民族的创世史诗

《黑暗传》与《荷马史诗》也确有不同特点，那便是《荷马史诗》属于英雄史诗，《黑暗传》则属于创世史诗，而且独具体汉民族的特色。

《黑暗传》以创世神话为构成主体，与世界上许多民族的创世神话相比，它更具想象的大胆性、离奇性、丰富性和科学性。西方民族的创世神话，只有《旧约圣经》中的《创世纪》能自成体系，但讲的十分简单，多是上帝说什么，世上便有了什么，基本没有什么情节。《黑暗传》则大不相同，它不认为上帝是唯一的造物主，而是讲万物和人类的创造是众多创世始祖的功劳，而且创造的历程是漫长而艰辛的。《黑暗传》展示的创世体系可用下表表示：


[cols="3*^.^",width="100%",options="header"]
|====================
| 历史阶段 | 创世始祖 |  主要功业
.3+| 先天 | 黑暗老祖|  宇内黑色由深变浅
| 混沌老祖 | 造出了海洋
| 玄黄老祖 | 出现了"生天之根"
.4+| 后天 .4+| 盘古 | 开天辟地
|日月升天
|创造万物
|初造人类
.3+|泡天| 鸿儒 |平息三番洪水
|弘皓|再造人类
|弘钧|
.8+|治世| 天皇 | 分四季
|地皇| 分日月
|人皇| 分九州
|伏羲| 创八卦制婚姻
|神农| 创农耕兴医药
|轩辕| 华夏族成一统
|唐尧| 扫妖孽兴禅让
|虞舜| 治洪水兴仁政
|====================

《黑暗传》所展示的创世历程富含科学因子。譬如，它解释生命起于海洋，这已为当代科学所证明。又譬如，它关于“先天”斗“后天斗“泡天”-“治世”的整体布局，“黑暗”斗“混沌”斗“玄黄”的渐变情况，“盘古开天”——“日月升天”——“人类初造”的演进历程等，无不闪烁着矛盾运动发展观、和谐观的光辉。再譬如，玄黄几经鏖战才最终取代了混沌，揭示的当是旧事物不甘心灭亡，但终将被新事物所代替的客观规律……

#### 《黑暗传》内容极为珍贵

《黑暗传》内容极为珍贵，除了上述创世历程的完整性和科学性外，还当表现在以下方面：

* 其一，《黑暗传》中的许多人物都少见经传。譬如黑暗老祖、混沌老祖、 玄黄老祖和弘钧、弘皓、弘儒三兄妹等。

* 其二，《黑暗传》中的许多故事都人物都鲜为人知。譬如江沽造水、浪荡吞天等。

* 其三，《黑暗传》中许多解释独具汉民族文化特点。譬如，印度和西方神话都讲洪水是上帝为惩罚人类而发的，《黑暗传》则解释为人类社会形成过程中难逃的劫难，因而更具本土特色。又譬如，葫芦兄妹与伏羲女娲本是两个故事，《黑暗传朋IJ将之连为一体，因而更显精彩动人。

* 其四，《黑暗传》是经历了漫长的创作历程才逐步成型的。在其形成过程中，它不断从外地和多民族创世神话里吸取了营养，而且善于对相关故事进行改造，因此内容既尽聚多民族、多地区创世神话于一体，思想尽融道、佛、儒文化于一体，体系却独具一色。

#### 《黑暗传》绝非渊源于《开辟演义》

有学者说，“《黑暗传》的内容渊源于明清的通俗小说《开辟演义通俗志传》（以下简称《开辟演义》）。相对于有三千年文学史的汉民族来说，仅有三百年历史的《黑暗传》是不能称为汉民族的史诗的，”因此也不能被视为非物质文化遗产。此说是难以成立的！

* 其一、《开辟演义》故事共八十回，从“盘古氏开天辟地”讲起，到“周武王吊民伐罪”结束。它虽以“开辟”为题，却并非全属开辟神话，因四十二回“尧帝康衢听童谣”以后的内容都当来自于“正史”。《黑暗传》则大不一样， 故事从宇宙本原讲起，不知道比盘古早了多少亿万年；讲到大禹治水为止，内容全属创世神话。

* 其二，盘古故事虽然为两者所共有，但说法却大相径庭。《开辟演义》 说盘古是被西方佛祖派来的，《黑暗传》则讲盘古孕育在昆仑山下，是五行聚化而成的，因而更合道教理论。

* 其三，《开辟演义》是明人周游的小说，《黑暗传》却是典型的民间口传文学作品，是无数无名歌手集体智慧的结晶。虽然明清之际也曾有过木刻本问世，但仍然以口头传承为主，神农架已经搜集到了十几个版本的资料，内容梗概大致相同，但相关故事的情节却不尽一致，当是因歌手们师承不同、风格各异造成。

#### 《黑暗传》急需保护与抢救

《中国民族民间文化保护工程实施方案》指出，“当前，面临着来自全球化和现代化的挑战，我国民族民间传统文化生存环境急剧恶化，保护状况堪忧。”“采取有效措施，加强我国民族民间传统文化的保护，已刻不容缓。”《黑暗传》也当在“刻不容缓”的保护之列。

《黑暗传》内容博大精深，又受到“孔子不语怪力与乱神”封建正统观念的排斥，所以历来会唱、敢唱的歌手一直很少。时至当今，“传承后继乏人”便成了最难解决的问题。笔者曾调查过神农架林区松柏镇的歌手情况，发现总数不超过30人，年龄大都在50岁以上，40多岁的寥寥无几，没有一人在40岁以下。他们中不仅早没有了能唱《黑暗传》全本的，就是能唱片段的也所剩无几。

应该说《黑暗传》基本已经失传，至少也是濒临失传了。当前的任务除了积极保护老歌手、多方培养新歌手外，抢救工作当在继续搜集资料的基础上，合各地、各方之力，精心予以研究，尽快整理出一个内容更为完整的本子。
